
Article.create(title: "How to create Blogger", body: "do all of this stuff")
Article.create(title: "Turing stuff", body: "This is a bunch of stuff about Turing")
Article.create(title: "Running out of Titles", body: "I'm not very creative")
Comment.create(author_name: "Joe", body: "stuff", article_id: 1)
Comment.create(author_name: "Joseph", body: "more stuff", article_id: 2)
Comment.create(author_name: "Joey", body: "even more stuff", article_id: 3)
Tag.create(name: "ruby")
Tag.create(name: "java")
Tag.create(name: "python")
Tagging.create(article_id: 1, tag_id: 1)
Tagging.create(article_id: 2, tag_id: 2)
Tagging.create(article_id: 3, tag_id: 3)
